subprojects {
    if (["applications", "components"].contains(name)) return

    group "io.collective"

    apply plugin: "java-library"

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    defaultTasks "clean", "build"

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation "com.fasterxml.jackson.core:jackson-core:2.8.4"
        implementation "com.fasterxml.jackson.core:jackson-databind:2.8.4"
        implementation "com.fasterxml.jackson.core:jackson-annotations:2.8.4"
        implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.8.4"
        implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.4"
        implementation "org.slf4j:slf4j-api:1.7.10"
        implementation "org.slf4j:slf4j-simple:1.7.10"

        testImplementation "junit:junit:4.11"
        testImplementation "org.mockito:mockito-core:3.3.0"
    }

    sourceSets {
        test.resources.srcDir "src/test/resources"
    }

    test.testLogging.showStandardStreams = true
    test.testLogging.exceptionFormat = "full"

    task stage(dependsOn: ["assemble", "clean"]) {
        group "Heroku"
        description "Run by Heroku to when deploying (https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku)"
    }
    assemble { mustRunAfter "clean" }
}
